### ISSUE TITLE
doesn't work with juno rc2

### ISSUE THREAD

**Issue by matthewfischer** [SUSE-Cloud/keystone-hybrid-backend#18]
When using this with the juno rc2 I'm getting some stracktraces, I'll see what I can dig up and update it here.

2014-10-15 14:05:05.011 20936 DEBUG keystone.identity.backends.hybrid_identity [-] Called get_user_by_name Matt, default get_user_by_name /usr/lib/python2.7/dist-packages/keystone/identity/backends/hybrid_identity.py:120
2014-10-15 14:05:05.170 20936 ERROR keystone.common.wsgi [-] tuple index out of range
2014-10-15 14:05:05.170 20936 TRACE keystone.common.wsgi Traceback (most recent call last):
2014-10-15 14:05:05.170 20936 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 223, in **call**
2014-10-15 14:05:05.170 20936 TRACE keystone.common.wsgi     result = method(context, **params)
2014-10-15 14:05:05.170 20936 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/dist-packages/keystone/token/controllers.py", line 100, in authenticate
2014-10-15 14:05:05.170 20936 TRACE keystone.common.wsgi     context, auth)
2014-10-15 14:05:05.170 20936 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/dist-packages/keystone/token/controllers.py", line 298, in _authenticate_local
2014-10-15 14:05:05.170 20936 TRACE keystone.common.wsgi     raise exception.Unauthorized(e.args[0])
2014-10-15 14:05:05.170 20936 TRACE keystone.common.wsgi IndexError: tuple index out of range

**Comment by matthewfischer** [comment]
The issue here is this snippet of code in token/controllers.py:

```
    try:
        user_ref = self.identity_api.authenticate(
            context,
            user_id=user_id,
            password=password)
    except AssertionError as e:
        raise exception.Unauthorized(e.args[0])
```

In the case we have e.args is empty, so e.args[0] generates an IndexError.

Will keep digging.

**Comment by matthewfischer** [comment]
In case I dont get a PR made tonight, here's the change I needed:

diff --git a/hybrid_identity.py b/hybrid_identity.py
index 1a33923..2d33c37 100644
--- a/hybrid_identity.py
+++ b/hybrid_identity.py
@@ -57,7 +57,8 @@ class Identity(sql_ident.Identity):
         try:
             # if the user_ref has a password, it's from the SQL backend and
             # we can just check if it coincides with the one we got
-            assert utils.check_password(password, user_ref['password'])
-            hashed_pw = utils.hash_password(password)
-            assert utils.check_password(password, hashed_pw)
       except TypeError:
           raise AssertionError('Invalid user / password')
       except KeyError:  # if it doesn't have a password, it must be LDAP

I also needed python-ldap 2.3 due to https://bugs.launchpad.net/keystone/+bug/1381768 which upstream is fixing.

**Comment by rhafer** [comment]
This has been fixed some time ago. AFAIK the icehouse branch should work for juno as well.
