### ISSUE TITLE
Not working with kilo release (resolved)

### ISSUE THREAD

**Issue by gkissandrakis** [SUSE-Cloud/keystone-hybrid-backend#34]
It was working fine with havana, with some modifications with juno
but in kilo openstack release does not work at all

2015-07-03 15:35:26.525 2601 ERROR keystone.common.wsgi [-] get_all_filtered() takes exactly 2 arguments (1 given)
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi Traceback (most recent call last):
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 239, in **call**
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi     result = method(context, *_params)
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/dist-packages/keystone/identity/controllers.py", line 50, in get_users
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi     CONF.identity.default_domain_id)
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/dist-packages/keystone/common/manager.py", line 47, in wrapper
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi     return f(self, *args, *_kwargs)
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/dist-packages/keystone/identity/core.py", line 342, in wrapper
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi     return f(self, _args, *_kwargs)
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/dist-packages/keystone/identity/core.py", line 353, in wrapper
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi     return f(self, _args, *_kwargs)
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/dist-packages/keystone/identity/core.py", line 791, in list_users
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi     ref_list = driver.list_users(hints)
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/dist-packages/keystone/identity/backends/hybrid_identity.py", line 138, in list_users
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi     ldap_users = self.user.get_all_filtered()
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi TypeError: get_all_filtered() takes exactly 2 arguments (1 given)
2015-07-03 15:35:26.525 2601 TRACE keystone.common.wsgi

**Comment by gkissandrakis** [comment]
line 139 in hybrid_identity.py
before
  ldap_users = self.user.get_all_filtered()
after
  ldap_users = self.user.get_all_filtered(hints)

**Comment by rhafer** [comment]
The "kilo" branch does exist now and should work with kilo
