### ISSUE TITLE
'module' object has no attribute 'Role'

### ISSUE THREAD

**Issue by tomboy67** [SUSE-Cloud/keystone-hybrid-backend#35]
kilo openstack release does not work.

on `devel` branch.

``` shell
$ keystone user-list
```

```
2015-07-14 19:10:37.345 960 DEBUG keystone.identity.backends.hybrid_identity [-] Authenticated user with SQL. authenticate /usr/lib/python2.7/site-packages/keystone/identity/backends/hybrid_identity.py:76
2015-07-14 19:10:37.459 960 ERROR keystone.common.wsgi [-] 'module' object has no attribute 'Role'
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi Traceback (most recent call last):
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/common/wsgi.py", line 239, in __call__
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi     result = method(context, **params)
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/token/controllers.py", line 101, in authenticate
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi     context, auth)
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/token/controllers.py", line 309, in _authenticate_local
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi     user_id, tenant_id)
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/token/controllers.py", line 387, in _get_project_roles_and_ref
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi     user_id, tenant_id)
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/assignment/core.py", line 167, in get_roles_for_user_and_project
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi     user_role_list = _get_user_project_roles(user_id, project_ref)
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/assignment/core.py", line 142, in _get_user_project_roles
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi     tenant_id=project_ref['id'])
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/assignment/backends/hybrid_assignment.py", line 40, in _get_metadata
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi     roles.append({'id': self.default_role})
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/assignment/backends/hybrid_assignment.py", line 56, in default_role
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi     role = session.query(sql_assign.Role).filter_by(
2015-07-14 19:10:37.459 960 TRACE keystone.common.wsgi AttributeError: 'module' object has no attribute 'Role'
```

**Comment by rhafer** [comment]
This was fixed in the kilo branch recently.
