### ISSUE TITLE
get_session missing

### ISSUE THREAD

**Issue by alex-leonhardt** [SUSE-Cloud/keystone-hybrid-backend#6]
Hi,

I just tried to use this but when trying to authenticate, I get : 

``` python
2014-08-11 11:07:08.097 50942 ERROR keystone.common.wsgi [-] 'Identity' object has no attribute 'get_session'
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi Traceback (most recent call last):
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/common/wsgi.py", line 207, in __call__
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi     result = method(context, **params)
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/token/controllers.py", line 98, in authenticate
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi     context, auth)
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/token/controllers.py", line 272, in _authenticate_local
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi     password=password)
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/notifications.py", line 253, in wrapper
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi     result = f(wrapped_self, context, user_id, *args, **kwargs)
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/identity/core.py", line 189, in wrapper
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi     return f(self, *args, **kwargs)
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/identity/core.py", line 281, in authenticate
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi     ref = driver.authenticate(user_id, password)
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/identity/backends/hybrid_identity.py", line 45, in authenticate
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi     session = self.get_session()
2014-08-11 11:07:08.097 50942 TRACE keystone.common.wsgi AttributeError: 'Identity' object has no attribute 'get_session'

```

We're using Icehouse, if that helps ? Not a good programmer, but if I can help to fix that, let me know.

Thanks!
Alex

**Comment by matthewfischer** [comment]
The code as posted does not work on Icehouse. My branch works but it works
in a different manner. There's also a pull request to fix it.

https://github.com/matthewfischer/keystone-hybrid-backend

**Comment by alex-leonhardt** [comment]
thanks @matthewfischer !
